sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
install:
  - npm i
jobs:
  include:
    - stage: build
      script:
        - npm run build:prod
    - stage: test
      script:
        - npm run test:unit
      after_success:
        - npm run test:unit:report
